DATAPREP:
  TESTDATA:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits

SIM:
  TRAININGSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 0.3
      RANSEED_REPEAT: 10 12345

  TESTSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
      DNDZ_ALLSCALE: 1.0
    GLOBAL:
      NGEN_UNIT: 0.2
      RANSEED_REPEAT: 5 12345

  IADES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 0.3
      RANSEED_REPEAT: 10 12345

  CCONLY:
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
    II_TEMPLATES:
      BASE: sn_ii_templates.input
    GLOBAL:
      NGEN_UNIT: 0.3
      RANSEED_REPEAT: 5 12345

LCFIT:
  TESTFIT:
    BASE: des.nml

CLASSIFICATION:
  SNNVANILLATRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK: TRAINING
    OPTS:
      USE_PHOTOMETRY: True

  SNNVANILLATEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      USE_PHOTOMETRY: True
      MODEL: SNNVANILLATRAIN

AGGREGATION:
  AGG:

MERGE:
  MERGE:

BIASCOR:
  BIASCOR:
    DATA: TESTDATA
    SIMFILE_BIASCOR: IADES
    SIMFILE_CCPRIOR: CCONLY
    CLASSIFIER: SNNVANILLATEST