SIM: # Dont change
  BORINGDES: # Sim name
    IA_G10: # Starts with IA_
      BASE: sn_ia_salt2_g10.input
    IA_C11: # Starts with IA_
      BASE: sn_ia_salt2_c11.input
      # GENMAG_SMEAR_MODELNAME: C11 # You can specify GENOPTS like this if you want, just dont need any atm
    IAX:
      BASE: sn_iax.input
      DNDZ_ALLSCALE: 5.0
    IA91BG:
      BASE: sn_ia91bg.input
      DNDZ_ALLSCALE: 10.0
    IBC_MOSFIT:
      BASE: sn_ibc_mosfit.input
      DNDZ_ALLSCALE: 2.0
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
      DNDZ_ALLSCALE: 17.0
    II_NMF:
      BASE: sn_ii_nmf.input
      DNDZ_ALLSCALE: 5.0
    II_TEMPLATES:
      BASE: sn_ii_templates.input
      DNDZ_ALLSCALE: 5.0
    GLOBAL:
      NGEN_UNIT: 0.5
LCFIT: # Dont change
  NOCHANGES: # Name of the light curve fitting
      BASE: des.nml
      MASK: DES # LCFIT MASK means only apply this light curve fitting on sims which have DES in the sim name, like BORINGDES
#  DIFFERENT_SN:
#      BASE: des.nml
#      FITOPTS: des.fitopts
#      SNLCINP:
#          CUTWIN_SNRMAX:  3.0, 1.0E8
#          CUTWIN_NFILT_SNRMAX:  3.0, 99.

CLASSIFICATION: # Dont change this
  TOY: # Name of the classification step
    CLASSIFIER: ToyClassifier
